version: '1.0-build_{build}'
image: Visual Studio 2022
#skip_branch_with_pr: true
configuration: Debug
platform:
  - Any CPU

branches:
  only:
    - master
    - develop
    - /\d*\.\d*\.\d*/

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(APPVEYOR_REPO_TAG_NAME)
  package_version: $(APPVEYOR_REPO_TAG_NAME)
  assembly_version: $(APPVEYOR_REPO_TAG_NAME)
  file_version: $(APPVEYOR_REPO_TAG_NAME)
  informational_version: $(APPVEYOR_REPO_TAG_NAME)

init:
  - ps: git config --global core.autocrlf input
  - ps: dotnet nuget locals http-cache -c
  - ps: dotnet tool install --global coverlet.console

before_build:
  - ps: ls
  - ps: dotnet restore
  - choco install opencover.portable
  - choco install codecov

build:
  project: Funx.sln
  verbosity: minimal

test_script:
  - ps: dotnet test tests/Funx/Funx.Tests.csproj --verbosity normal
#  - ps: ls ./tests/Funx/bin/
#  - ps: ls ./tests/Funx/bin/Debug
#  - ps: ls ./tests/Funx/bin/Debug/netcoreapp3.1
  - ps: coverlet .\tests\Funx\bin\Debug\net8.0\Funx.Tests.dll --target "dotnet" --targetargs "test --no-build" --format "opencover" --output "./funx_coverage.xml"
  - codecov -f "funx_coverage.xml"
    
after_test:
  - ps: dotnet build src/Funx/Funx.csproj -c Release
  - ps: dotnet pack src/Funx/Funx.csproj --no-restore --no-build -c Release -o ./publish
  - ps: ls ./publish

artifacts:
  - path: '**\*.nupkg'

deploy:
  -
    provider: NuGet
    api_key:
      secure: u+tz8/wLjX6sQ/KNA4jNZiihA5nXhWQx8JjUDt0kLlg8VBJHEzToNL3A9miswDAf
    skip_symbols: false
    artifact: /.*\.nupkg/

#for:
#-
#  branches:
#    only:
#      - /\d+\.\d+\.\d+/
#
#  configuration: Release
#
#  test_script:
#    - ps: dotnet test tests/Funx/Funx.Tests.csproj --verbosity normal
#    - ps: coverlet .\tests\Funx\bin\Release\net8.0\Funx.Tests.dll --target "dotnet" --targetargs "test --no-build" --format "opencover" --output "./funx_coverage.xml"
#    - codecov -f "funx_coverage.xml"
#
#  after_test:
#    - ps: dotnet pack src/Funx/Funx.csproj --no-restore --no-build -c Release -o ./publish
#    - ps: ls ./publish
#
#  artifacts:
#    - path: '**\*.nupkg'
#
#  deploy:
#    provider: NuGet
#    api_key:
#      secure: u+tz8/wLjX6sQ/KNA4jNZiihA5nXhWQx8JjUDt0kLlg8VBJHEzToNL3A9miswDAf
#    skip_symbols: false
#    artifact: /.*\.nupkg/
