version: '1.0.{build}'
image: Visual Studio 2019
skip_branch_with_pr: true
configuration: Release
platform: x64
init:
  - ps: ls
build:
  verbosity: normal
test:
  assemblies:
    only:
      - ./tests/Nyx.Tests
deploy:
  - provider: NuGet
    api_key:
      secure: UNhG2ePtkOWC4kyxRzHWPVYv5GM+QgT1/8S3aVsU3Vyrhag1VnzaN7jUe7vxcZZJ
