version: '1.0-build_{build}'
image: Visual Studio 2017
#skip_branch_with_pr: true
configuration: Release
platform:
  - Any CPU

branches:
  only:
    - /\d*\.\d*\.\d*/

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(APPVEYOR_REPO_TAG_NAME)
  package_version: $(APPVEYOR_REPO_TAG_NAME)
  assembly_version: $(APPVEYOR_REPO_TAG_NAME)
  file_version: $(APPVEYOR_REPO_TAG_NAME)
  informational_version: $(APPVEYOR_REPO_TAG_NAME)


init:
  - ps: git config --global core.autocrlf input
  - ps: dotnet nuget locals http-cache -c

before_build:
  - ps: ls
  - ps: dotnet restore

build_script:
  - ps: dotnet build src/Funx/Funx.csproj --verbosity m

test_script:
  - ps: dotnet test tests/Funx/Funx.Tests.csproj --verbosity normal

after_test:
  - ps: dotnet pack src/Funx/Funx.csproj --no-restore --no-build -c Release -o ../../publish
  - ps: ls publish
#  - appveyor PushArtifact publish/Funx.1.0.0.nupkg

artifacts:
  - path: '**\*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: 1mdi2SiGn3xkp9/LhAaeBi032LeQ2fOuKFNm06P++VhPTcHbbv+AsA73iraxGT2S
  skip_symbols: false
  artifact: /.*\.nupkg/


on_success:
  - ps: Write-Host "All Done" -ForegroundColor DarkGreen -BackgroundColor White
